### ISSUE TITLE
Can't read and send messages

### ISSUE THREAD

**Issue by rollingmoai** [ChrisEric1/chriseric1.github.io#1]
![image](https://user-images.githubusercontent.com/75471378/175804093-dd1730e2-bc86-4d02-b861-7f6a5a7c4725.png)

**Comment by CE1CECL** [comment]
What browser are you using?
Did you try the extension? https://chriseric1.github.io/extension.zip
I still need to write a README, I didn't know someone would already find this tho, but in chrome, extract the zip, goto chrome://extensions and load the unpacked zip in dev mode.

you can also try the app https://github.com/ChrisEric1/ChrisEric1.github.io/releases

but as of now, most emojis still dont work due to the fact that they have to be copied from discords server
and emojis is a tough one to do.

**Comment by CE1CECL** [comment]
i also noticed this doesnt need an extension if you login with a user (non bot, in the browser console), which is really strange, but after all, i only fixed the patched version from @flam3rboy so it might need a rewrite. Would love for someone to send a PR if anyone bothers a complete rewrite from scratch, I'm not sure why bots need CORS, and users dont, but thats discord.

**Comment by rollingmoai** [comment]
> you can also try the app [ChrisEric1/ChrisEric1.github.io/releases](https://github.com/ChrisEric1/ChrisEric1.github.io/releases)

Hmm 🤔
![image](https://user-images.githubusercontent.com/75471378/175821758-0d2c9f8e-5d0f-430f-b2df-7de67f53cc12.png)

> I still need to write a README, I didn't know someone would already find this tho, but in chrome, extract the zip, goto chrome://extensions and load the unpacked zip in dev mode.

I can clone the repo and use the `extension` folder too, right?

> I still need to write a README, I didn't know someone would already find this tho

Just me randomly searching on GitHub 😅

**Comment by rollingmoai** [comment]
Okay, the extension is loaded. Now how do I use it?

**Comment by CE1CECL** [comment]
> > you can also try the app [ChrisEric1/ChrisEric1.github.io/releases](https://github.com/ChrisEric1/ChrisEric1.github.io/releases)
> 
> Hmm 🤔 ![image](https://user-images.githubusercontent.com/75471378/175821758-0d2c9f8e-5d0f-430f-b2df-7de67f53cc12.png)
> 
> > I still need to write a README, I didn't know someone would already find this tho, but in chrome, extract the zip, goto chrome://extensions and load the unpacked zip in dev mode.
> 
> I can clone the repo and use the `extension` folder too, right?
> 
> > I still need to write a README, I didn't know someone would already find this tho
> 
> Just me randomly searching on GitHub 😅

The app is electron/'s npm i && npm dist,
and the extension, yes you could clone it, since its just zipped up

**Comment by CE1CECL** [comment]
> Okay, the extension is loaded. Now how do I use it?

just go back to the website
its just a fix for the site, to load messages

**Comment by CE1CECL** [comment]
let me know if it works or not

**Comment by rollingmoai** [comment]
Ooh, right. It works now. Thanks! Certainly needs to be documented.

**Comment by rollingmoai** [comment]
> i also noticed this doesnt need an extension if you login with a user (non bot, in the browser console), which is really strange, but after all, i only fixed the patched version from @Flam3rboy so it might need a rewrite. Would love for someone to send a PR if anyone bothers a complete rewrite from scratch, I'm not sure why bots need CORS, and users dont, but thats discord.

Can you fix the version from https://github.com/Lightcord/Lightcord though? That also has a bot login and is more latest in terms of new features (replies and such).

**Comment by CE1CECL** [comment]
> > i also noticed this doesnt need an extension if you login with a user (non bot, in the browser console), which is really strange, but after all, i only fixed the patched version from @Flam3rboy so it might need a rewrite. Would love for someone to send a PR if anyone bothers a complete rewrite from scratch, I'm not sure why bots need CORS, and users dont, but thats discord.
> 
> Can you fix the version from https://github.com/Lightcord/Lightcord though? That also has a bot login and is more latest in terms of new features (replies and such).

maybe, if i knew what was wrong, for sure yes. But i think its BBD thats the issue, I would love to use messagelogger in my bot too, and the new features, but Lightcord seems to be a little too big of a mess in its current state. I would need to still understand the gateway a little more tho (and reverse these things). If you want to FR me, you can @ ChrisEric1 CECL#5569

**Comment by CE1CECL** [comment]
@itsmeboy0 i could try to run the 202X assets from discord into lightcord, i can get the numbers needed from web.archive.org but i dont remember when it stopped working, do you know? If not, ill try them all from Jul 28, 2021, until it stops working. I still need to figure out how to load the correct assets and not the newest ones tho. Also, do you know anymore bot clients that are based off the discord asset system? Other than LightCord and this one in this repo.

**Comment by sitiom** [comment]
It is safe to assume that it was still working by the time it was archived (around October 2021).

**Comment by CE1CECL** [comment]
@rollingmoai I fixed lightcord, the patches are in https://github.com/ChrisEric1/ChrisEric1 so what you have to do is run lightcord once, let it "load" for the "first" time, and completely close lightcord. Then goto "%APPDATA%\lightcord\" in file explorer (assuming this is windows) and download my ChrisEric1 repo mentioned earlier. Replace settings.json from my repo into lightcord's folder. Now you need to run index.js from my repo using node.js. Run 'npm i' in the folder downloaded and then when it installs, run 'node index.js'. You may now run lightcord. If it doesn't load right away, close lightcord again and re-open it again (don't reload the local server, index.js). You can download lightcord from the official archived repo, or use my fork and compile it, if you do compile it, you dont need to patch settings.json, but you do still need the server as of now. And yes, @sitiom is correct, lightcord broken sometime in October 25 of 2021, which i got the last assets from the wayback machine and used them. I hope this is clear, if not, anyone feel free to re-ask here and ill do my best to clear it up.

**Comment by rollingmoai** [comment]
It's a wall of text, but I understood it, thanks. I noticed I have to run `index.js` in the background every time I want to open up Lightcord, which is quite inconvenient.

**Comment by rollingmoai** [comment]
@CE1CECL Whyd you put a messagelogger plugin in the repo 🧐 https://github.com/ChrisEric1/ChrisEric1/blob/main/MessageLoggerV2.plugin.js

**Comment by CE1CECL** [comment]
> @CE1CECL Whyd you put a messagelogger plugin in the repo monocle_face https://github.com/ChrisEric1/ChrisEric1/blob/main/MessageLoggerV2.plugin.js

oops, i meant to only upload 0pluginlibrary since it fetches the latest version that doesnt work. messagelogger doesnt even work tho, where it doesnt save, so i deleted it.

**Comment by CE1CECL** [comment]
i feel like lightcord is a mess of fetching links from all different random places for some reason it needs a cleanup at least in the case of ref links

**Comment by CE1CECL** [comment]
> It's a wall of text, but I understood it, thanks. I noticed I have to run `index.js` in the background every time I want to open up Lightcord, which is quite inconvenient.

The inconvenience is gone now: https://github.com/ChrisEric1/Lightcord/releases NOTE: Bugs that were in the patch may still be here, including that relaunch to work bug when launched for the first time. You shouldn't need to copy settings.json anymore (unless you want to use something else like lightcord) Also note that the script is embedded to port 2022, so you may need to disable firewall to port 2022 of localhost.

**Comment by CE1CECL** [comment]
I don't think tabs work for discord, especially when inside a bot (1020 CF ERR), can anyone confirm? The patch from before won't work b/c settings.json didn't apply to tabs for some reason.

**Comment by CE1CECL** [comment]
also Firefox extension is here https://github.com/ChrisEric1/ChrisEric1/releases
