### ISSUE TITLE
the servers wont load 

### ISSUE THREAD

**Issue by imcronus** [ChrisEric1/ChrisEric1.github.io#16]
there is just an exclamation mark and no servers

**Comment by CE1CECL** [comment]
Works fine for me, anything in console? (F12 -> Console)

**Comment by imcronus** [comment]
the servers finally loaded after about like 30 minutes is there anything i can do to get a faster load?

**Comment by CE1CECL** [comment]
Wondering how many servers the bot is in? It could be the issue.

**Comment by imcronus** [comment]
currently its 176

**Comment by CE1CECL** [comment]
Hmm I have a bot that is in 20 Servers ATM, and its doing the same thing, It worked before though, I will leave this issue open until I find something out on why this is happening. It doesn't seem to be the members list thing at PR #14 or #13 so I see whats going on, sorry I didn't get back sooner.

**Comment by CE1CECL** [comment]
Sorry, its only in 20 servers atm, and it works fine for me doesn't hang. I have to close this issue because I don't own a bot token with 150 servers.
