### ISSUE TITLE
bot client not loading

### ISSUE THREAD

**Issue by kngsvc** [ChrisEric1/ChrisEric1.github.io#18]
ever since the new update, i can't access the client! when i start up the website, it does not load and my screen appears as the image attached. any solutions pls? 
<img width="608" alt="Screenshot 2023-07-07 at 1 03 00 PM" src="https://github.com/ChrisEric1/ChrisEric1.GitHub.io/assets/89560385/42e462da-2156-4c08-bae8-dc1eac1d5ddc">

**Comment by CE1CECL** [comment]
> ever since the new update, i can't access the client! when i start up the website, it does not load and my screen appears as the image attached. any solutions pls? <img alt="Screenshot 2023-07-07 at 1 03 00 PM" width="608" src="https://user-images.githubusercontent.com/89560385/251640825-42e462da-2156-4c08-bae8-dc1eac1d5ddc.png">

Unfortunately, the update had to be reverted, due to the fact someone else had issue with them. You can try to clear your cache, or CTRL + F5, and if it still doesn't work, CTRL + SHIFT + I, then Console, screenshot any errors.

**Comment by CE1CECL** [comment]
Also are you using the app or the site?

**Comment by kngsvc** [comment]
ctrl + f5 and ctrl + shift + I does not do anything, and I'm using the site since i'm on mac and it has worked until this update

**Comment by CE1CECL** [comment]
> ctrl + f5 and ctrl + shift + I does not do anything, and I'm using the site since i'm on mac and it has worked until this update

May I ask what mac browser you are using, and if you can try private mode in your browser if available? I would have to get a hackintosh to get the app sent to you, which won't probably happen anytime soon though, sadly.

**Comment by CE1CECL** [comment]
also ctrl shift i is just right clicking and clicking inspect element or something similar, it just keyboard shortcuts, i don't know what they are supposed to be for macs, since they use command, option keys, etc..

**Comment by kngsvc** [comment]
i'm using chrome! Are these the errors i'm supposed to screenshot? 
<img width="553" alt="Screenshot 2023-07-08 at 10 28 18 AM" src="https://github.com/ChrisEric1/ChrisEric1.GitHub.io/assets/89560385/b92ddae0-29ce-4cc6-8b44-a09a5985c8ea">

**Comment by kngsvc** [comment]
oh the website works when on private browser though, thanks

**Comment by kngsvc** [comment]
i can open the website using private browser, but the messages don't load
<img width="876" alt="Screenshot 2023-07-08 at 10 32 44 AM" src="https://github.com/ChrisEric1/ChrisEric1.GitHub.io/assets/89560385/8d4fec57-b6d0-4366-ad59-c279f2f477c8">

**Comment by CE1CECL** [comment]
> i can open the website using private browser, but the messages don't load <img alt="Screenshot 2023-07-08 at 10 32 44 AM" width="876" src="https://user-images.githubusercontent.com/89560385/251892616-8d4fec57-b6d0-4366-ad59-c279f2f477c8.png">

Assuming the extension is installed, you will need to go to chrome://extensions and enable for the extension in private mode

**Comment by kngsvc** [comment]
i'm guessing i'm not able to enable extensions using private/incognito mode on chrome because it just takes me back to my normal browser, and i've enabled the extension on my normal browser first before opening it on private but it's the same

**Comment by CE1CECL** [comment]
> i'm guessing i'm not able to enable extensions using private/incognito mode on chrome because it just takes me back to my normal browser, and i've enabled the extension on my normal browser first before opening it on private but it's the same

It should take you back to your normal mode, but look under the extension settings to see if there is a switch for private mode, its usually disabled by default.

**Comment by kngsvc** [comment]
okay yeah that works! thanks

**Comment by CE1CECL** [comment]
> okay yeah that works! thanks

No problem!
