### ISSUE TITLE
The chat doest show peoples text

### ISSUE THREAD

**Issue by WhatOrWhy** [ChrisEric1/chriseric1.github.io#3]
any help?
![Screenshot_1](https://user-images.githubusercontent.com/53174007/195682028-6d2f30dc-dbc7-43d4-b448-c436e3ca1866.png)

**Comment by CE1CECL** [comment]
What are you trying to send? If its a sticker it won't work b/c its client is from 2020

**Comment by WhatOrWhy** [comment]
I can send texts, but I do not see other peoples text

**Comment by WhatOrWhy** [comment]
nvm I fixed it myself

**Comment by CE1CECL** [comment]
What did you do to fix it? I'm going to close this issue since i assume that what you mean by this:

> nvm I fixed it myself
