### ISSUE TITLE
Question: Do you log tokens?

### ISSUE THREAD

**Issue by NexorikMason** [ChrisEric1/chriseric1.github.io#6]
just asking do you log tokens?

like do tokens get send to any database after logged in?

**Comment by CE1CECL** [comment]
Not at all, the websites source code is this repo, mainly in 404.html, I used to log IP's before anyone pretty much knew about this but then I removed it for privacy and spam reasons.

**Comment by NexorikMason** [comment]
so i am 100% save putting my bot token in your client?

**Comment by CE1CECL** [comment]
How else do you log in to the bot? (AKA Yes you do)

**Comment by NexorikMason** [comment]
just wanna make sure since i got some stuff stolen from me some time ago lol

ty for the answer means alot

**Comment by CE1CECL** [comment]
> just wanna make sure since i got some stuff stolen from me some time ago lol
> 
> ty for the answer means alot

From LC or the old client, If the LC dev's log the token, I am not sure where they would in the code but the WC is 100% clean.

**Comment by NexorikMason** [comment]
wait this is based on Lightcord?

**Comment by CE1CECL** [comment]
No, this is the @flam3rboy client, there are 2 clients, one you download is LC, and the Web is completely a different version of the Discord client

**Comment by NexorikMason** [comment]
i downloaded the 32bit release of 1.0.0

**Comment by NexorikMason** [comment]
its basicly a modded lightcord project?

**Comment by CE1CECL** [comment]
Oh the one on this repo is just chrome embedded of the website, you should be fine

**Comment by NexorikMason** [comment]
OH THANK GOD

FOR A SECOND I THOUGHT I WAS GONNA BE DEAD INA WEEK LOL

aslong as i know this app isnt stealing my infomation am more then happy to use this

**Comment by CE1CECL** [comment]
Wait, whats wrong with LC, is it a stealer?

**Comment by NexorikMason** [comment]
not that i know?

i used lightcord before its shut down

my account did get token logged but that was by a hacker not by Lightcord

so far ik of course

**Comment by CE1CECL** [comment]
Ah ok, thats the official repo I cloned and modded to work again.

**Comment by NexorikMason** [comment]
wait but you said they stole tokens? and ips? am confused

**Comment by CE1CECL** [comment]
I dont know, I dont think they do tho, I dont except ce1cecl.xyz Homepage, thats it

**Comment by NexorikMason** [comment]
so i should be save right if i use this ?
![image](https://user-images.githubusercontent.com/112890419/197843039-cc4385e7-3b25-4462-a8af-df51f6c19b2f.png)

**Comment by CE1CECL** [comment]
yes

**Comment by NexorikMason** [comment]
okay then ty for your time

https://github.com/Lightcord/Lightcord/discussions/318
