### ISSUE TITLE
Changing the bot's status seem to doesn't work

### ISSUE THREAD

**Issue by CE1CECL** [ChrisEric1/chriseric1.github.io#7]
Does not change status of the bot for other users to see, I change my bot to dnd, regular discord shows online. This is major if you want to have it invisible or if there are too many discord notifications and want to silence them.

**Comment by CE1CECL** [comment]
https://github.com/ChrisEric1/ChrisEric1.GitHub.io/commit/e545da2ec8c9a0dfda6287e85b4bbfdf9d8a5d5b seems to fix it, must of been forcing to stay online all the time, but when i refresh, it stays dnd, on one end it doesnt update unless i change to online and back to dnd. But thats a minor issue, at least I think it is.

**Comment by aiko-chan-ai** [comment]
I fixed some things in the Lightcord version, I will open a pull request if you agree :3

**Comment by CE1CECL** [comment]
> I fixed some things in the Lightcord version, I will open a pull request if you agree :3

Yes please do, as I was having a hard time cleaning up that repo without breaking it (if thats what you were even doing)!

**Comment by aiko-chan-ai** [comment]
@CE1CECL https://github.com/ChrisEric1/Lightcord/pull/2 here
