### ISSUE TITLE
It is not showing message of people

### ISSUE THREAD

**Issue by NotSureYT** [ChrisEric1/chriseric1.github.io#8]
hi Idk why but it don't show messages like its invisible

you can see in picture I uploaded 
![coz i dunno](https://user-images.githubusercontent.com/106507462/206460243-75714ab8-64a8-4102-bc94-f9aeb7deb9ae.PNG)

**Comment by CE1CECL** [comment]
![Capture](https://user-images.githubusercontent.com/52040854/206468944-03cf033c-4752-40fb-ac5c-b3f70c673932.PNG)

Are you able to send out? If so, this is a duplicate of https://github.com/ChrisEric1/ChrisEric1.GitHub.io/issues/3 but I cannot tell which was is the bot.

**Comment by aiko-chan-ai** [comment]
maybe ...
![image](https://user-images.githubusercontent.com/71698422/206854111-ec2ba51d-1223-4aa9-8d1e-9ae34d5ee348.png)

**Comment by CE1CECL** [comment]
> maybe ... ![image](https://user-images.githubusercontent.com/71698422/206854111-ec2ba51d-1223-4aa9-8d1e-9ae34d5ee348.png)

![Capture](https://user-images.githubusercontent.com/52040854/206859630-d2c6dab0-447b-4cc4-9097-e06bd968b312.PNG)
Yes, but no, it works fine for me like this still, but when I use my non-bot acc, it doesn't show unless I check that option. This is without it:
![Capture](https://user-images.githubusercontent.com/52040854/206859709-5f4c34ba-99da-4116-ac7b-a23545bcd9a3.PNG)

They were backslashes, but when I turned it on for my bot, then I could see the newer messages if I don't refresh the page. I didn't realize this would be needed, but this actually is an issue if you cannot verify with discord and use DBC (as it says once it reaches 100+ servers)

**Comment by NotSureYT** [comment]
Thanks

**Comment by NotSureYT** [comment]
It is fixed

**Comment by NotSureYT** [comment]
You can close this issue now
